---
all:
  children:
    node_exporters:
      hosts:
        stg-app-01:
          ansible_host: 100.56.229.83
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /root/.ssh/k8s.pem
